sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ivanovadev/docker-react123 -f Dockerfile.dev .

script:
  - docker run -e CI=true ivanovadev/docker-react123 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: 'docker-react'
  env: 'docker-env'
  bucket_name: "elasticbeanstalk-eu-north-1-111218800953"
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
